---
driver:
  name: vagrant
  customize:
    memory: 4096
  gui: false

driver_config:
  network:
    - ["forwarded_port", { guest: 8800, host: 8800 }]
    - ["forwarded_port", { guest: 80, host: 8080 }]
    - ["forwarded_port", { guest: 443, host: 8443 }]

provisioner:
  sudo: true
  name: chef_zero
  product_name: chef
  product_version: latest
  chef_license: accept
  install_strategy: always
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: bento/ubuntu-22.04
  - name: bento/ubuntu-24.04
  - name: bento/rockylinux-8
  - name: bento/rockylinux-9

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
