name 'terraform_enterprise'
maintainer 'HashiCorp'
maintainer_email 'hello@hashicorp.com'
license 'Apache-2.0'
description 'Installs/Configures Terraform Enterprise (Replicated installer)'
version '1.1.0'
chef_version '>= 18.0'

issues_url 'https://github.com/mtharpe/chef-terraform-enterprise/issues'
source_url 'https://github.com/mtharpe/chef-terraform-enterprise'

supports 'ubuntu', '>= 22.04'
supports 'debian', '>= 12.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'almalinux', '>= 8.0'
