version: 2.1

executors:
  chef-workstation:
    docker:
      - image: cimg/ruby:3.3
    working_directory: ~/cookbook

jobs:
  lint:
    executor: chef-workstation
    steps:
      - checkout
      - run:
          name: Install Cookstyle
          command: gem install --no-document cookstyle
      - run:
          name: Cookstyle
          command: cookstyle --display-cop-names .

workflows:
  validate:
    jobs:
      - lint
